language: go
sudo: required

go:
  - '1.12.x'

services:
  - docker

env:
  global:
    - GO111MODULE=on

go_import_path: github.com/bblfsh/performance

install:
  - go mod download
  - go generate ./...

before_deploy:
  - make packages

deploy:
  if: branch = ci-integration
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build/*.tar.gz
  skip_cleanup: true
  on:
    tags: true

after_deploy:
  - DOCKER_PUSH_LATEST=1 make docker-push